import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.Pane;

import java.io.IOException;

/**
 * The controller class for the main menu of the "Frog dominating world chips challenge" game.
 * This class handles user interactions in the main menu, such as starting the game or exiting the application.
 *
 * @author Shane Lee, Aeron Vergara
 * @version 1.5
 */
public class TestController {

    @FXML
    private Button exit;

    @FXML
    private Button highScore;

    @FXML
    private Button play;

    /**
     * Handles the "Play" button click event by transitioning to the game's user interface.
     *
     * @param event The action event generated by clicking the "Play" button.
     */
    @FXML
    void play(ActionEvent event) {
        try {
            Pane root = FXMLLoader.load(getClass().getResource("Fxml/user.fxml"));
            MainMenuTest.mainScene.setRoot(root);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    /**
     * Handles the "Exit" button click event by closing the application.
     *
     * @param event The action event generated by clicking the "Exit" button.
     */
    @FXML
    void exit(ActionEvent event) {

        System.exit(0);

    }

    /**
     * Handles the "High Score" button click event by transitioning to the high score screen.
     *
     * @param event The action event generated by clicking the "High Score" button.
     */
    @FXML
    void highScore(ActionEvent event) {
        try {
            Pane root = FXMLLoader.load(getClass().getResource("Fxml/highScore.fxml"));
            MainMenuTest.mainScene.setRoot(root);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}